[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    'reactive-lib/=lib/reactive-lib/src/'
]
